### ISSUE TITLE
SSINS Model Import Error

### ISSUE THREAD

**Issue by tamerakassie** [mwilensky768/SSINS#122]
Is there a way to work around this error:

Python 3.8.10 (default, Mar 13 2023, 10:26:41) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from SSINS import SS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/idia/users/tamera/SSINsWD/SSINS/SSINS/__init__.py", line 15, in <module>
    from . import version as _version
ImportError: cannot import name 'version' from partially initialized module 'SSINS' (most likely due to a circular import) (/idia/users/tamera/SSINsWD/SSINS/SSINS/__init__.py)
>>>

**Comment by tamerakassie** [comment]
Hi @mwilensky768 I installed SSINS in a Virtual Environment, Linux os, The issue above resolved when I changed the pyuvdata  dependency (setuptools_scm>=7.0.3,<7.0 to setuptools_scm>=7.0.3,<8.0).  Thank You

**Comment by mwilensky768** [comment]
Thanks @tamerakassie !
