### ISSUE TITLE
Run_HERA_SSINS does not support partial I/O on visibilities

### ISSUE THREAD

**Issue by jsdillon** [mwilensky768/SSINS#64]
I'm not too familiar with how SSINS works, but if it would be possible to achieve the same result without loading in all the data simultaneously, this would make it far easier to parallelize.  XRFI, for example, has an option to only load N waterfalls at a time, process them down to a single metric waterfall, and then load the next batch, and so on.

https://github.com/mwilensky768/SSINS/blob/101999fc03e156c457ff3a974a0fb4e77ee8c851/scripts/Run_HERA_SSINS.py#L41

**Comment by mwilensky768** [comment]
So, the way this talks to `hera_opm`, it should just read in one `chunk_size` worth of files. Do you want it to be able to further chunk the chunks?

**Comment by jsdillon** [comment]
No, it should load all times in the chunk, but only some of the baselines at a time (ideally).

**Comment by mwilensky768** [comment]
Closed by #66
